# Start with a rustup.sh image.
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# native dependencies
# before_script:
# - apt-get update -yqq
# - apt-get install -yqq --no-install-recommends gcc libsqlite3-dev libsqlite3-0 libpq-dev libmysqlclient-dev

# Use cargo to test the project
test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --verbose
  cache:
    paths:
      - target/
